name: Continuous Deployment (prod)

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_SECRET}}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push shaka image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: aliabbaschadhar003/shaka-app:${{github.sha}}
        
      - name: Clone my-ops repo, update image tags, and push tags
        env:
          PAT: ${{secrets.PAT}}
        run: |
          git clone https://github.com/aliabbaschadhar/my-ops.git
          cd my-ops

          sed -i 's|image: aliabbaschadhar003/shaka-app:.*|image: aliabbaschadhar003/shaka-app:${{github.sha}}|' manifest.yml

          git config user.name "Github Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update shaka app image tags to ${{github.sha}}"
          git push https://${PAT}@github.com/aliabbaschadhar/my-ops.git main